bookish_speed.settings:
  type: config_object
  label: 'Bookish Speed settings'
  mapping:
    wait_time:
      type: integer
      label: 'Wait time'
    exclude_regex:
      type: string
      label: 'Exclude paths'
