lunr.lunr_search.*:
  type: config_entity
  label: 'Lunr search'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    path:
      type: path
      label: 'Path'
    view_id:
      type: string
      label: 'View ID'
    view_display_id:
      type: string
      label: 'View display ID'
    index_fields:
      type: sequence
      label: 'Index fields'
      sequence:
        type: mapping
        label: 'Attributes'
        mapping:
          boost:
            type: integer
            label: 'Boost'
    display_field:
      type: string
      label: 'Display field'
    results_per_page:
      type: integer
      label: 'Results per page'

views.display.lunr_search_index:
  type: views_display_path
  label: 'Lunr search index display options'
  mapping:
    auth:
      type: sequence
      label: 'Authentication'
      sequence:
        type: string
        label: 'Authentication Provider'

views.row.lunr_search_index_row:
  type: views_row
  label: 'Field row'
  mapping:
    field_options:
      type: sequence
      label: 'Options'
      sequence:
        type: mapping
        label: 'Row'
        mapping:
          alias:
            type: string
            label: 'Alias for ID'
          raw_output:
            type: boolean
            label: 'Raw output for ID'

views.style.lunr_search_index_json:
  type: views_style
  label: 'Serialized output format'

lunr_search_block:
  type: block_settings
  label: 'Lunr search block'
  mapping:
    lunr_search_id:
      type: label
      lable: 'Lunr search ID'

block.settings.lunr_search:*:
  type: lunr_search_block
