highlight_php.settings:
  type: config_object
  label: 'Highlight PHP settings'
  mapping:
    mode:
      type: string
      label: 'The highlight mode - either "manual" or "auto"'
    auto_languages:
      type: string
      label: 'A list of languages to auto-detect, if using the "auto" mode'
    manual_regex:
      type: string
      label: 'A regular expression ran against the <code> tag where the first group matches the language to detect.'
